spring.application.name=ParkingTask

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.url=jdbc:postgresql://postgres:5432/student_db1
#spring.datasource.username=admin
#spring.datasource.password=admin
#spring.datasource.username=admin
#spring.datasource.password=admin
spring.datasource.username=postgres
spring.datasource.password=NewPassword123


logging.file.name=logs/parking.log
logging.level.root=INFO

jwt.secret=Ajr4NN1wlHy21uM5tzf5kjSynAwLRaQVnTIYdRANCaH
jwt.expiration=1800000

weather.api.key=de5f78cb5bc9b8dedad49d2bc639aca4
#@Value("${weather.api.key}")
#private String apiKey;

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
###update,create,none-jpa

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


